 SELECT (elem.value ->> '_id'::text) AS subproduct_id,
    ((elem.value -> 'brand'::text) ->> '_id'::text) AS brand_id,
    ((elem.value -> 'brand'::text) ->> 'name'::text) AS brand_name,
    (elem.value ->> 'category'::text) AS category,
    ((elem.value -> 'commision'::text) ->> 'commissionId'::text) AS commission_id,
    ((elem.value -> 'commision'::text) ->> 'level'::text) AS commission_level,
    ((elem.value -> 'commision'::text) ->> 'pct'::text) AS commission_pct,
    ((elem.value -> 'individualSummary'::text) ->> 'productPrice'::text) AS ind_product_price,
    ((elem.value -> 'individualSummary'::text) ->> 'adjustmentPrice'::text) AS ind_adjustment_price,
    ((elem.value -> 'individualSummary'::text) ->> 'shippingfee'::text) AS ind_shipping_fee,
    ((elem.value -> 'individualSummary'::text) ->> 'commission'::text) AS ind_commission,
    ((elem.value -> 'individualSummary'::text) ->> 'vat'::text) AS ind_vat,
    ((elem.value -> 'individualSummary'::text) ->> 'buypassProfit'::text) AS ind_buypass_profit,
    ((elem.value -> 'individualSummary'::text) ->> 'otherDeductions'::text) AS ind_other_deductions,
    ((elem.value -> 'individualSummary'::text) ->> 'productTotal'::text) AS ind_product_total,
    ((elem.value -> 'individualSummary'::text) ->> 'packageHandling'::text) AS ind_package_handling,
    ((elem.value -> 'individualSummary'::text) ->> 'cashHandlingFee'::text) AS ind_cash_handling_fee,
    ((elem.value -> 'individualSummary'::text) ->> 'tax'::text) AS ind_tax,
    ((elem.value -> 'overallItemSummary'::text) ->> 'productPrice'::text) AS overall_product_price,
    ((elem.value -> 'overallItemSummary'::text) ->> 'adjustmentPrice'::text) AS overall_adjustment_price,
    ((elem.value -> 'overallItemSummary'::text) ->> 'shippingfee'::text) AS overall_shipping_fee,
    ((elem.value -> 'overallItemSummary'::text) ->> 'commission'::text) AS overall_commission,
    ((elem.value -> 'overallItemSummary'::text) ->> 'vat'::text) AS overall_vat,
    ((elem.value -> 'overallItemSummary'::text) ->> 'buypassProfit'::text) AS overall_buypass_profit,
    ((elem.value -> 'overallItemSummary'::text) ->> 'otherDeductions'::text) AS overall_other_deductions,
    ((elem.value -> 'overallItemSummary'::text) ->> 'productTotal'::text) AS overall_product_total,
    ((elem.value -> 'overallItemSummary'::text) ->> 'packageHandling'::text) AS overall_package_handling,
    ((elem.value -> 'overallItemSummary'::text) ->> 'cashHandlingFee'::text) AS overall_cash_handling_fee,
    ((elem.value -> 'overallItemSummary'::text) ->> 'tax'::text) AS overall_tax,
    (elem.value ->> 'isAvailable'::text) AS is_available,
    (elem.value ->> 'isReview'::text) AS is_review,
    (elem.value ->> 'orderType'::text) AS order_type,
    (elem.value ->> 'ordignalQuantity'::text) AS original_quantity,
    (elem.value ->> 'price'::text) AS price,
    (elem.value ->> 'productId'::text) AS product_id,
    (elem.value ->> 'productImage'::text) AS product_image,
    (elem.value ->> 'productName'::text) AS product_name,
    (elem.value ->> 'productUnavailablityReason'::text) AS product_unavailability_reason,
    (elem.value ->> 'quantity'::text) AS quantity,
    (elem.value ->> 'shippingFee'::text) AS shipping_fee,
    (elem.value ->> 'sku'::text) AS sku,
    (elem.value ->> 'specialPrice'::text) AS special_price,
    (elem.value -> 'variants'::text) AS variants,
    (elem.value -> 'weight'::text) AS weight,
    t._id,
    t.address__id,
    t.address_addresstype,
    t.address_area,
    t.address_city,
    t.address_cityid,
    t.address_coordinates,
    t.address_isdefaultbillingaddress,
    t.address_isdefaultshippingaddress,
    t.address_landmark,
    t.address_neighbourhood,
    t.address_neighbourhoodid,
    t.address_phonenumber,
    t.address_recipientname,
    t.address_state,
    t.address_stateid,
    t.address_streetaddress,
    t.address_type,
    t.address_userid,
    t.address_zip,
    t.address_zone,
    t.address_zoneid,
    t.assignrider__id,
    t.assignrider_email,
    t.assignrider_name,
    t.assignrider_phonenumber,
    t.assignrider_profilepicture_metadata_height,
    t.assignrider_profilepicture_metadata_width,
    t.assignrider_profilepicture_metadata_filetype,
    t.assignrider_profilepicture_metadata_fileformat,
    t.assignrider_profilepicture_metadata_name,
    t.assignrider_profilepicture_metadata_duration,
    t.assignrider_profilepicture_type,
    t.assignrider_profilepicture_url,
    t.assignridertime,
    t.awbdate,
    t.buyerstatus,
    t.buypassid,
    t.cancellationreason,
    t.createdon,
    t.deliveredtime,
    t.deliverypartner,
    t.dropoffproof,
    t.ecommerceshipment_consignmentno,
    t.ecommerceshipment_referenceid,
    t.ecommerceshipment_refrenceid,
    t.id,
    t.influencerid,
    t.isbuynow,
    t.isdeleted,
    t.islambdainvoked,
    t.isquickcommerce,
    t.isresponsetimeextended,
    t.isreturn,
    t.isreviewed,
    t.items,
    t.logisticpartner_logisticid,
    t.logisticpartner_title,
    t.marketingcampaignid,
    t.modifiedon,
    t.orderaccepttime,
    t.orderid,
    t.orderpackageimage,
    t.ordersummary_adjustmentamount,
    t.ordersummary_adjustmentprice,
    t.ordersummary_buypasscommission,
    t.ordersummary_buypassprofit,
    t.ordersummary_cashhandlingfee,
    t.ordersummary_commission,
    t.ordersummary_deliverycharges,
    t.ordersummary_discount,
    t.ordersummary_otherdeduction,
    t.ordersummary_packagehandling,
    t.ordersummary_sellerprice,
    t.ordersummary_shippingfeesubtotal,
    t.ordersummary_shippingfee,
    t.ordersummary_subtotal,
    t.ordersummary_tax,
    t.ordersummary_total,
    t.ordersummary_totalcartitems,
    t.ordersummary_totalorderweight,
    t.ordersummary_vat,
    t.paymentmethoddata__id,
    t.paymentmethoddata_name,
    t.paymentmethoddata_shortname,
    t.paymentmethoddata_description,
    t.pickupproof,
    t.preparingtime,
    t.rideid,
    t.riderinvoicedate,
    t.sellercancellationreason,
    t.sellerdetails__id,
    t.sellerdetails_address,
    t.sellerdetails_buypassid,
    t.sellerdetails_city,
    t.sellerdetails_coordinates,
    t.sellerdetails_email,
    t.sellerdetails_phonenumber,
    t.sellerdetails_photourl,
    t.sellerdetails_storeid,
    t.sellerdetails_storename,
    t.sellerdetails_type,
    t.sellerstatus,
    t.shippingmethod__id,
    t.shippingmethod_name,
    t.shippingmethod_shippingtype,
    t.slabrechedtiming,
    t.statementid,
    t.status,
    t.statushistory,
    t.timeline_cancelledtime,
    t.trackingnumber,
    t.type,
    t.usercreated,
    t.userdetails__id,
    t.userdetails_buypassid,
    t.userdetails_city,
    t.userdetails_email,
    t.userdetails_name,
    t.userdetails_phonenumber,
    t.userdetails_profilepicture_sellerid,
    t.userdetails_profilepicture_folderid,
    t.userdetails_profilepicture_url,
    t.userdetails_profilepicture_type,
    t.userdetails_profilepicture_metadata_height,
    t.userdetails_profilepicture_metadata_width,
    t.userdetails_profilepicture_metadata_filetype,
    t.userdetails_profilepicture_metadata_fileformat,
    t.userdetails_profilepicture_metadata_name,
    t.userdetails_profilepicture_metadata_duration,
    t._corrupt_record,
    elem.value
   FROM (stg.orders t
     CROSS JOIN LATERAL jsonb_array_elements((t.items)::jsonb) elem(value));