 SELECT _id,
    birthday,
    buypassid,
    createdon,
    email,
    fullname,
    gender,
    id,
    isdeleted,
    iss3imagesadded,
    modifiedon,
    phonenumber,
    profilepicture_firebaseurl,
    profilepicture_metadata_height,
    profilepicture_metadata_width,
    profilepicture_metadata_filetype,
    profilepicture_metadata_fileformat,
    profilepicture_metadata_name,
    profilepicture_metadata_duration,
    profilepicture_url,
    userid,
    _corrupt_record,
    ('week-'::text || ((((EXTRACT(day FROM createdon))::integer - 1) / 7) + 1)) AS week_in_month,
    to_char(createdon, 'Mon'::text) AS month_name,
    (EXTRACT(month FROM createdon))::integer AS month_number,
    (EXTRACT(year FROM createdon))::integer AS year,
    ((to_char(createdon, 'Mon'::text) || '-W'::text) || ((((EXTRACT(day FROM createdon))::integer - 1) / 7) + 1)) AS month_week_label
   FROM stg.keycloak_users;